<section class="section">
    <form action="index.php?controller=user&action=save" method="POST" class="container">
        <div class="field">
            <div class="control"><input type="text" class="input" placeholder="Nom complet" name="full_name"></div>
        </div>
        <div class="field">
            <div class="control"><input type="text" class="input" placeholder="Ema" name="email"></div>
        </div>
        <div class="field">
            <div class="control"><input type="text" class="input" placeholder="URL de votre avatar" name="image_url"></div>
        </div>
        <div class="field">
            <div class="control">
                <textarea name="description" class="textarea" placeholder="Votre description en quelques mots"></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control"><input type="password" class="input" placeholder="Mot de passe" name="password"></div>
        </div>
        <div class="field">
            <div class="control"><input type="password" class="input" placeholder="Confirmation de mot de passe" name="password_confirm"></div>
        </div>
        
        <div class="field">
            <div class="control"><button type="submit" class="button is-success">Inscription</button></div>
        </div>
    </form>
</section>