<section class="section">
    <form action="index.php?controller=user&action=auth" method="POST" class="container">
        
        <div class="field">
            <div class="control"><input type="text" class="input" placeholder="Adresse email" name="email"></div>
        </div>
        <div class="field">
            <div class="control"><input type="text" class="input" placeholder="Mot de passe" name="password"></div>
        </div>
        <div class="field">
            <div class="control">
                <button type="submit" class="button is-success">Connexion !</button>
            </div>
        </div>
        
    </form>
</section>