<h1>Inscription</h1>
    <form action="save-user.php" method="POST">
        <input type="text" name =firstName placeholder ="prenom">
        <input type="text" name="lastName" placeholder =" nom de famille">
        <input type="email" name="email" placeholder ="email">
        <input type="password" name ="password" placeholder ="Mot de passe">
        <button type="submit">Valider!</button>
    </form>