<header id="admin">  
    <?php if($_SESSION['connected']) : ?>
        <nav>
            <a href="reservation.php">Réservations</a>
            <a href="commandes.php">Commandes</a>
            <a href="plats.php">Liste des plats</a>
            <a href="new.php">Créer un plat</a>
            <a href="../index.php">Voir le site</a>
            <a href="deconnexion.php">Déconnexion</a>
        </nav>
    <?php endif; ?>
</header>
    
    