<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="css/main.css" type="text/css" />
		<script type="text/javascript" src='JS/utilitaires.js'></script>
		<script type="text/javascript" src="ckeditor/ckeditor.js"></script>
		<title>Blog intéractif</title>
	</head>
	<body>
	    <header>
	        <div>
	            <h1>Blog de Maman</h1>
		        <?php
		        require('templates/nav.phtml');
		        ?>
	        </div>
	    </header>
	    <main>