
<section class="section">
    <div class="container">
        <h2 class="title">
            Les annonces de la catégorie<?= $category->title ?>
        </h2>
        <div class="columns is-multiline">
            <?php foreach($derniers as $annonce) : ?>
                <div class="column is-one-quarter">
                    <div class="card">
                      <div class="card-image">
                        <figure class="image is-4by3">
                          <img src="index.php?action=show&id=<?= $annonce->id ?>" alt="<?= $annonce->title ?>">
                        </figure>
                      </div>
                      <div class="card-content">
                        <div class="media">
                          <div class="media-content">
                            <p class="title is-4">
                                <?= $annonce->title ?>
                            </p>
                            <p class="subtitle is-6">
                                <a href="#">
                                    <?= $annonce->full_name ?>    
                                </a>
                            </p>
                          </div>
                        </div>
                    
                        <div class="content">
                          <p>
                              <?= $annonce->short_description ?>
                          </p>
                          <hr>
                          <a href="index.php?action=show&id=<?= $annonce->id ?>" class="button is-primary">Voir l'annonce</a>
                        </div>
                      </div>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>