<section class="section container">
    <form action="index.php?action=save" method='POST'>
        <div class="field">
            <div class="control">
                <input type="text" class="input" name="title" placeholder="Titre de l'annonce" value=""/>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" class="input" name="price" placeholder="Prix de l'image" value=""/>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" class="input"  name="image_url" placeholder="Url de l'image" value="" />
            </div>
        </div>
        <div class="field">
            <div class="control">
                <textarea class="textarea" name="short_description"  placeholder="Description courte de l'annonce"></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <textarea class="textarea" name="description"  placeholder="Description complète de l'annonce"></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <div class="select is-fullwidth">
                    <select name="category_id" >
                       <?php foreach ($categories as $category): ?>
                       <option value="<?= $category->id?>"><?= $category->title ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>  
        <div class="field">
            <div class="control">
                <button type="submit" class="button is-success" value="">Enregistrer</button>
            </div>
        </div>
    </form>
</section>