<section class="section container">
    <form action="index.php?action=edit" method='POST'>
        <div class="field">
            <div class="control">
                <input type="text" class="input" name="title" placeholder="Titre de l'annonce" value="<?= $annonce->title ?>"/>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" class="input" name="price" placeholder="Prix de l'image" value="<?= $annonce-> price ?>"/>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <input type="text" class="input"  name="image_url" placeholder="Url de l'image" value="<?= $annonce->image_url ?>" />
            </div>
        </div>
        <div class="field">
            <div class="control">
                <textarea class="textarea" name="short_description"  placeholder="Description courte de l'annonce"><?= $annonce->short_description ?></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <textarea class="textarea" name="description"  placeholder="Description complète de l'annonce"><?= $annonce->description ?></textarea>
            </div>
        </div>
        <div class="field">
            <div class="control">
                <div class="select is-fullwidth">
                    <select name="category_id" >
                       <?php foreach ($categories as $category): ?>
                            <?php if($annonce->category_id == $category->id) : ?>
                                <option value="<?= $category->id?>" selected><?= $category->title ?></option>
                            <?php else : ?>
                                <option value="<?= $category->id?>"><?= $category->title ?></option>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </div>  
        <div class="field">
            <div class="control">
                <button type="submit" class="button is-success" value="<?= $annonce->id ?>">Enregistrer</button>
            </div>
        </div>
        <input type = "hidden" name = "id" value="<?= $annonce->id ?>">
    </form>
</section>