<form action="libraries/tasks.php?task=update" method="POST">
    <h2>Modifier un article</h2>
    <input type="text" name="title" placeholder="Titre de l'article" value="<?= $article['title'] ?>">
    <input type="text" name="image_url" placeholder="URL de l'image" value="<?= $article['image_url'] ?>">
    
    <select name="category_id">
        <?php foreach($categories as $categorie) : ?>
            <option value="<?= $categorie['id'] ?>"><?= $categorie['title'] ?></option>
        <?php endforeach ?>
    </select>
    
    <textarea name="introduction" placeholder="Introduction de l'article (texte court)"><?= $article['introduction'] ?></textarea>
    <textarea name="content" placeholder="Contenu de l'article (texte long)"><?= $article['content'] ?></textarea>
    
    <input type="hidden" name="id" value="<?= $article['id'] ?>" />
    
    <button type="submit" class="special success">Enregistrer</button>
</form>