<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css" />
        <link rel="stylesheet" href="css/main.css" type="text/css" />
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav> 
                <a href="index.php">Accueil RESTAUWEB</a>
                <a href="reservation.php">Réservez votre table</a>
                <a href="confirmerCommande.php">Voir le panier</a>
            </nav>
        </header>
        <main>