<h1>Réservez votre table!</h1>

<form action="utilitaires/resa.php" method="POST">
            <input type="text" name="fullName" placeholder="Votre nom">
            <input type="text" name ="personNumber" placeholder="nombre de personne">
            <input type="date" name="dateResa">
            <input type="tel" name="telephone" placeholder="téléphone">
            <button type="submit">Valider la commande</button>
</form>